[package]
name    = "current-service"
version = "0.1.0"
edition = "2021"

[dependencies]
current-domain      = { path = "../domain" }
current-persistence = { path = "../persistence" }
sqlx               = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
uuid               = { version = "1", features = ["v4", "serde"] }
chrono             = { version = "0.4", features = ["serde"] }
serde              = { version = "1", features = ["derive"] }
thiserror          = "1"
tokio              = { version = "1", features = ["full"] }
